language: c
before_install:
    - sudo apt-get install valgrind
    - mkdir /home/travis/deps
    - ./install_deps.sh /home/travis/deps
    - sudo pip install cpp-coveralls
install: libtoolize && ./autogen.sh && ./configure
compiler:
    - gcc
script: make check
env:
    global:
        - TWITC_KEY=A TWITC_SECRET=B TWITC_ACCESS_TOKEN=C TWITC_ACCESS_SECRET=D
        - CFLAGS="-I/home/travis/deps/include -L/home/travis/deps/lib"
after_failure:
    - ls /home/travis/build/sinemetu1/twitc/src
    - ls /home/travis/build/sinemetu1/twitc/src/test
    - cat /home/travis/build/sinemetu1/twitc/src/test-suite.log
    - cat /home/travis/build/sinemetu1/twitc/src/test/test_reply.log
    - cat /home/travis/build/sinemetu1/twitc/src/test/test_twitc.log
after_success:
    - make check-valgrind
    - ./configure --enable-gcov && make clean coverage && coveralls -b src/ --no-gcov
