language: c
before_install:
- sudo apt-get install valgrind
- ./install_deps.sh
install: 
compiler:
- gcc
- clang
script: ./autogen.sh && ./configure && make check
env:
    global:
        - TWITC_KEY=A TWITC_SECRET=B TWITC_ACCESS_TOKEN=C TWITC_ACCESS_SECRET=D
